// GENERATED FILE, DO NOT EDIT.
// Run `pnpm --filter @repo/ui generate:registry` after adding a component,
// a demo, a brick or an icon. The build fails if this file is out of date.

/** Families of components, and where each one lives. */
export const FAMILIES = [
  { id: 'ui', codeDir: 'src/components', docsSegment: 'elements/ui' },
  { id: 'layout', codeDir: 'src/layout', docsSegment: 'elements/layout' },
  { id: 'ai', codeDir: 'src/ai', docsSegment: 'elements/ai' },
  { id: 'hybrids', codeDir: 'src/hybrids', docsSegment: 'elements/hybrids' },
] as const;

export const COMPONENT_REGISTRY = {
  accordion: 'packages/ui/src/components/accordion.tsx',
  actions: 'packages/ui/src/ai/actions.tsx',
  'agent-run': 'packages/ui/src/hybrids/agent-run.tsx',
  'aspect-ratio': 'packages/ui/src/layout/aspect-ratio.tsx',
  attachment: 'packages/ui/src/components/attachment.tsx',
  attachments: 'packages/ui/src/ai/attachments.tsx',
  avatar: 'packages/ui/src/components/avatar.tsx',
  badge: 'packages/ui/src/components/badge.tsx',
  banner: 'packages/ui/src/components/banner.tsx',
  breadcrumb: 'packages/ui/src/components/breadcrumb.tsx',
  bubble: 'packages/ui/src/components/bubble.tsx',
  button: 'packages/ui/src/components/button.tsx',
  callout: 'packages/ui/src/components/callout.tsx',
  card: 'packages/ui/src/components/card.tsx',
  center: 'packages/ui/src/layout/center.tsx',
  'chain-of-thought': 'packages/ui/src/ai/chain-of-thought.tsx',
  chat: 'packages/ui/src/hybrids/chat.tsx',
  checkbox: 'packages/ui/src/components/checkbox.tsx',
  'code-block': 'packages/ui/src/ai/code-block.tsx',
  collapsible: 'packages/ui/src/components/collapsible.tsx',
  command: 'packages/ui/src/components/command.tsx',
  composer: 'packages/ui/src/hybrids/composer.tsx',
  confirm: 'packages/ui/src/hybrids/confirm.tsx',
  container: 'packages/ui/src/layout/container.tsx',
  context: 'packages/ui/src/ai/context.tsx',
  'context-menu': 'packages/ui/src/components/context-menu.tsx',
  conversation: 'packages/ui/src/ai/conversation.tsx',
  'data-table': 'packages/ui/src/hybrids/data-table.tsx',
  dialog: 'packages/ui/src/components/dialog.tsx',
  dock: 'packages/ui/src/components/dock.tsx',
  drawer: 'packages/ui/src/components/drawer.tsx',
  'dropdown-menu': 'packages/ui/src/components/dropdown-menu.tsx',
  empty: 'packages/ui/src/components/empty.tsx',
  field: 'packages/ui/src/components/field.tsx',
  'file-upload': 'packages/ui/src/components/file-upload.tsx',
  flex: 'packages/ui/src/layout/flex.tsx',
  frame: 'packages/ui/src/components/frame.tsx',
  grid: 'packages/ui/src/layout/grid.tsx',
  'hover-card': 'packages/ui/src/components/hover-card.tsx',
  'icon-tile': 'packages/ui/src/components/icon-tile.tsx',
  input: 'packages/ui/src/components/input.tsx',
  kbd: 'packages/ui/src/components/kbd.tsx',
  label: 'packages/ui/src/components/label.tsx',
  message: 'packages/ui/src/components/message.tsx',
  'navigation-menu': 'packages/ui/src/components/navigation-menu.tsx',
  pagination: 'packages/ui/src/components/pagination.tsx',
  popover: 'packages/ui/src/components/popover.tsx',
  progress: 'packages/ui/src/components/progress.tsx',
  'prompt-input': 'packages/ui/src/ai/prompt-input.tsx',
  radio: 'packages/ui/src/components/radio.tsx',
  rating: 'packages/ui/src/components/rating.tsx',
  reasoning: 'packages/ui/src/ai/reasoning.tsx',
  resizable: 'packages/ui/src/components/resizable.tsx',
  response: 'packages/ui/src/ai/response.tsx',
  'scroll-area': 'packages/ui/src/components/scroll-area.tsx',
  'search-command': 'packages/ui/src/hybrids/search-command.tsx',
  section: 'packages/ui/src/layout/section.tsx',
  select: 'packages/ui/src/components/select.tsx',
  separator: 'packages/ui/src/components/separator.tsx',
  'settings-row': 'packages/ui/src/hybrids/settings-row.tsx',
  sheet: 'packages/ui/src/components/sheet.tsx',
  shimmer: 'packages/ui/src/ai/shimmer.tsx',
  skeleton: 'packages/ui/src/components/skeleton.tsx',
  snippet: 'packages/ui/src/components/snippet.tsx',
  sources: 'packages/ui/src/ai/sources.tsx',
  spacer: 'packages/ui/src/layout/spacer.tsx',
  spinner: 'packages/ui/src/components/spinner.tsx',
  split: 'packages/ui/src/layout/split.tsx',
  sprite: 'packages/ui/src/components/sprite.tsx',
  stack: 'packages/ui/src/layout/stack.tsx',
  steps: 'packages/ui/src/components/steps.tsx',
  suggestion: 'packages/ui/src/ai/suggestion.tsx',
  switch: 'packages/ui/src/components/switch.tsx',
  table: 'packages/ui/src/components/table.tsx',
  tabs: 'packages/ui/src/components/tabs.tsx',
  task: 'packages/ui/src/ai/task.tsx',
  textarea: 'packages/ui/src/components/textarea.tsx',
  timeline: 'packages/ui/src/components/timeline.tsx',
  toast: 'packages/ui/src/components/toast.tsx',
  tool: 'packages/ui/src/ai/tool.tsx',
  tooltip: 'packages/ui/src/components/tooltip.tsx',
  tree: 'packages/ui/src/components/tree.tsx',
  typography: 'packages/ui/src/components/typography.tsx',
} as const;

/** Which family each component belongs to. */
export const COMPONENT_FAMILY = {
  accordion: 'ui',
  actions: 'ai',
  'agent-run': 'hybrids',
  'aspect-ratio': 'layout',
  attachment: 'ui',
  attachments: 'ai',
  avatar: 'ui',
  badge: 'ui',
  banner: 'ui',
  breadcrumb: 'ui',
  bubble: 'ui',
  button: 'ui',
  callout: 'ui',
  card: 'ui',
  center: 'layout',
  'chain-of-thought': 'ai',
  chat: 'hybrids',
  checkbox: 'ui',
  'code-block': 'ai',
  collapsible: 'ui',
  command: 'ui',
  composer: 'hybrids',
  confirm: 'hybrids',
  container: 'layout',
  context: 'ai',
  'context-menu': 'ui',
  conversation: 'ai',
  'data-table': 'hybrids',
  dialog: 'ui',
  dock: 'ui',
  drawer: 'ui',
  'dropdown-menu': 'ui',
  empty: 'ui',
  field: 'ui',
  'file-upload': 'ui',
  flex: 'layout',
  frame: 'ui',
  grid: 'layout',
  'hover-card': 'ui',
  'icon-tile': 'ui',
  input: 'ui',
  kbd: 'ui',
  label: 'ui',
  message: 'ui',
  'navigation-menu': 'ui',
  pagination: 'ui',
  popover: 'ui',
  progress: 'ui',
  'prompt-input': 'ai',
  radio: 'ui',
  rating: 'ui',
  reasoning: 'ai',
  resizable: 'ui',
  response: 'ai',
  'scroll-area': 'ui',
  'search-command': 'hybrids',
  section: 'layout',
  select: 'ui',
  separator: 'ui',
  'settings-row': 'hybrids',
  sheet: 'ui',
  shimmer: 'ai',
  skeleton: 'ui',
  snippet: 'ui',
  sources: 'ai',
  spacer: 'layout',
  spinner: 'ui',
  split: 'layout',
  sprite: 'ui',
  stack: 'layout',
  steps: 'ui',
  suggestion: 'ai',
  switch: 'ui',
  table: 'ui',
  tabs: 'ui',
  task: 'ai',
  textarea: 'ui',
  timeline: 'ui',
  toast: 'ui',
  tool: 'ai',
  tooltip: 'ui',
  tree: 'ui',
  typography: 'ui',
} as const;

export const DEMO_REGISTRY = {
  accordion: {
    collapsed: 'packages/ui/src/demos/accordion/collapsed.tsx',
    default: 'packages/ui/src/demos/accordion/default.tsx',
    multiple: 'packages/ui/src/demos/accordion/multiple.tsx',
  },
  actions: {
    default: 'packages/ui/src/demos/actions/default.tsx',
    'with-message': 'packages/ui/src/demos/actions/with-message.tsx',
  },
  'agent-run': {
    default: 'packages/ui/src/demos/agent-run/default.tsx',
    live: 'packages/ui/src/demos/agent-run/live.tsx',
  },
  'aspect-ratio': {
    default: 'packages/ui/src/demos/aspect-ratio/default.tsx',
    ratios: 'packages/ui/src/demos/aspect-ratio/ratios.tsx',
  },
  attachment: {
    cards: 'packages/ui/src/demos/attachment/cards.tsx',
    chips: 'packages/ui/src/demos/attachment/chips.tsx',
    default: 'packages/ui/src/demos/attachment/default.tsx',
    uploading: 'packages/ui/src/demos/attachment/uploading.tsx',
  },
  attachments: {
    default: 'packages/ui/src/demos/attachments/default.tsx',
    variants: 'packages/ui/src/demos/attachments/variants.tsx',
  },
  avatar: {
    'avatar-group': 'packages/ui/src/demos/avatar/avatar-group.tsx',
    default: 'packages/ui/src/demos/avatar/default.tsx',
    sizes: 'packages/ui/src/demos/avatar/sizes.tsx',
    'with-fallback': 'packages/ui/src/demos/avatar/with-fallback.tsx',
  },
  badge: {
    default: 'packages/ui/src/demos/badge/default.tsx',
    destructive: 'packages/ui/src/demos/badge/destructive.tsx',
    outline: 'packages/ui/src/demos/badge/outline.tsx',
    secondary: 'packages/ui/src/demos/badge/secondary.tsx',
    'with-icon': 'packages/ui/src/demos/badge/with-icon.tsx',
  },
  banner: {
    danger: 'packages/ui/src/demos/banner/danger.tsx',
    default: 'packages/ui/src/demos/banner/default.tsx',
    dismissible: 'packages/ui/src/demos/banner/dismissible.tsx',
    info: 'packages/ui/src/demos/banner/info.tsx',
    success: 'packages/ui/src/demos/banner/success.tsx',
    variants: 'packages/ui/src/demos/banner/variants.tsx',
    warning: 'packages/ui/src/demos/banner/warning.tsx',
  },
  breadcrumb: {
    collapsed: 'packages/ui/src/demos/breadcrumb/collapsed.tsx',
    'custom-separator': 'packages/ui/src/demos/breadcrumb/custom-separator.tsx',
    default: 'packages/ui/src/demos/breadcrumb/default.tsx',
  },
  bubble: {
    default: 'packages/ui/src/demos/bubble/default.tsx',
    variants: 'packages/ui/src/demos/bubble/variants.tsx',
  },
  button: {
    default: 'packages/ui/src/demos/button/default.tsx',
    destructive: 'packages/ui/src/demos/button/destructive.tsx',
    ghost: 'packages/ui/src/demos/button/ghost.tsx',
    link: 'packages/ui/src/demos/button/link.tsx',
    outline: 'packages/ui/src/demos/button/outline.tsx',
    secondary: 'packages/ui/src/demos/button/secondary.tsx',
    sizes: 'packages/ui/src/demos/button/sizes.tsx',
    variants: 'packages/ui/src/demos/button/variants.tsx',
  },
  callout: {
    danger: 'packages/ui/src/demos/callout/danger.tsx',
    default: 'packages/ui/src/demos/callout/default.tsx',
    info: 'packages/ui/src/demos/callout/info.tsx',
    success: 'packages/ui/src/demos/callout/success.tsx',
    variants: 'packages/ui/src/demos/callout/variants.tsx',
    warning: 'packages/ui/src/demos/callout/warning.tsx',
  },
  card: {
    compact: 'packages/ui/src/demos/card/compact.tsx',
    default: 'packages/ui/src/demos/card/default.tsx',
    ghost: 'packages/ui/src/demos/card/ghost.tsx',
    outline: 'packages/ui/src/demos/card/outline.tsx',
  },
  center: {
    axis: 'packages/ui/src/demos/center/axis.tsx',
    default: 'packages/ui/src/demos/center/default.tsx',
  },
  'chain-of-thought': {
    default: 'packages/ui/src/demos/chain-of-thought/default.tsx',
  },
  chat: {
    default: 'packages/ui/src/demos/chat/default.tsx',
    streaming: 'packages/ui/src/demos/chat/streaming.tsx',
  },
  checkbox: {
    default: 'packages/ui/src/demos/checkbox/default.tsx',
    disabled: 'packages/ui/src/demos/checkbox/disabled.tsx',
    'with-label': 'packages/ui/src/demos/checkbox/with-label.tsx',
  },
  'code-block': {
    collapsible: 'packages/ui/src/demos/code-block/collapsible.tsx',
    default: 'packages/ui/src/demos/code-block/default.tsx',
  },
  collapsible: {
    bordered: 'packages/ui/src/demos/collapsible/bordered.tsx',
    card: 'packages/ui/src/demos/collapsible/card.tsx',
    default: 'packages/ui/src/demos/collapsible/default.tsx',
  },
  command: {
    default: 'packages/ui/src/demos/command/default.tsx',
  },
  composer: {
    default: 'packages/ui/src/demos/composer/default.tsx',
    streaming: 'packages/ui/src/demos/composer/streaming.tsx',
  },
  confirm: {
    default: 'packages/ui/src/demos/confirm/default.tsx',
    hook: 'packages/ui/src/demos/confirm/hook.tsx',
    'with-text': 'packages/ui/src/demos/confirm/with-text.tsx',
  },
  container: {
    default: 'packages/ui/src/demos/container/default.tsx',
  },
  context: {
    default: 'packages/ui/src/demos/context/default.tsx',
  },
  'context-menu': {
    default: 'packages/ui/src/demos/context-menu/default.tsx',
  },
  conversation: {
    default: 'packages/ui/src/demos/conversation/default.tsx',
    streaming: 'packages/ui/src/demos/conversation/streaming.tsx',
  },
  'data-table': {
    compact: 'packages/ui/src/demos/data-table/compact.tsx',
    default: 'packages/ui/src/demos/data-table/default.tsx',
  },
  dialog: {
    alert: 'packages/ui/src/demos/dialog/alert.tsx',
    default: 'packages/ui/src/demos/dialog/default.tsx',
  },
  dock: {
    default: 'packages/ui/src/demos/dock/default.tsx',
    links: 'packages/ui/src/demos/dock/links.tsx',
  },
  drawer: {
    default: 'packages/ui/src/demos/drawer/default.tsx',
    form: 'packages/ui/src/demos/drawer/form.tsx',
    positions: 'packages/ui/src/demos/drawer/positions.tsx',
  },
  'dropdown-menu': {
    checkboxes: 'packages/ui/src/demos/dropdown-menu/checkboxes.tsx',
    default: 'packages/ui/src/demos/dropdown-menu/default.tsx',
    'radio-group': 'packages/ui/src/demos/dropdown-menu/radio-group.tsx',
  },
  empty: {
    default: 'packages/ui/src/demos/empty/default.tsx',
    outline: 'packages/ui/src/demos/empty/outline.tsx',
  },
  field: {
    default: 'packages/ui/src/demos/field/default.tsx',
    fieldset: 'packages/ui/src/demos/field/fieldset.tsx',
    horizontal: 'packages/ui/src/demos/field/horizontal.tsx',
    'with-error': 'packages/ui/src/demos/field/with-error.tsx',
  },
  'file-upload': {
    avatar: 'packages/ui/src/demos/file-upload/avatar.tsx',
    compact: 'packages/ui/src/demos/file-upload/compact.tsx',
    default: 'packages/ui/src/demos/file-upload/default.tsx',
    images: 'packages/ui/src/demos/file-upload/images.tsx',
    multiple: 'packages/ui/src/demos/file-upload/multiple.tsx',
    'upload-progress': 'packages/ui/src/demos/file-upload/upload-progress.tsx',
  },
  flex: {
    default: 'packages/ui/src/demos/flex/default.tsx',
  },
  frame: {
    default: 'packages/ui/src/demos/frame/default.tsx',
    stacked: 'packages/ui/src/demos/frame/stacked.tsx',
  },
  grid: {
    default: 'packages/ui/src/demos/grid/default.tsx',
  },
  'hover-card': {
    default: 'packages/ui/src/demos/hover-card/default.tsx',
    'link-preview': 'packages/ui/src/demos/hover-card/link-preview.tsx',
  },
  'icon-tile': {
    default: 'packages/ui/src/demos/icon-tile/default.tsx',
    radius: 'packages/ui/src/demos/icon-tile/radius.tsx',
    sizes: 'packages/ui/src/demos/icon-tile/sizes.tsx',
    text: 'packages/ui/src/demos/icon-tile/text.tsx',
    tones: 'packages/ui/src/demos/icon-tile/tones.tsx',
    variants: 'packages/ui/src/demos/icon-tile/variants.tsx',
  },
  input: {
    default: 'packages/ui/src/demos/input/default.tsx',
    disabled: 'packages/ui/src/demos/input/disabled.tsx',
    sizes: 'packages/ui/src/demos/input/sizes.tsx',
    'with-error': 'packages/ui/src/demos/input/with-error.tsx',
    'with-icon': 'packages/ui/src/demos/input/with-icon.tsx',
    'with-label': 'packages/ui/src/demos/input/with-label.tsx',
  },
  kbd: {
    default: 'packages/ui/src/demos/kbd/default.tsx',
    sizes: 'packages/ui/src/demos/kbd/sizes.tsx',
    variants: 'packages/ui/src/demos/kbd/variants.tsx',
    'with-group': 'packages/ui/src/demos/kbd/with-group.tsx',
  },
  label: {
    default: 'packages/ui/src/demos/label/default.tsx',
    required: 'packages/ui/src/demos/label/required.tsx',
  },
  message: {
    default: 'packages/ui/src/demos/message/default.tsx',
    grouped: 'packages/ui/src/demos/message/grouped.tsx',
  },
  'navigation-menu': {
    badges: 'packages/ui/src/demos/navigation-menu/badges.tsx',
    default: 'packages/ui/src/demos/navigation-menu/default.tsx',
  },
  pagination: {
    compact: 'packages/ui/src/demos/pagination/compact.tsx',
    default: 'packages/ui/src/demos/pagination/default.tsx',
  },
  popover: {
    default: 'packages/ui/src/demos/popover/default.tsx',
  },
  progress: {
    default: 'packages/ui/src/demos/progress/default.tsx',
    indeterminate: 'packages/ui/src/demos/progress/indeterminate.tsx',
    'with-value': 'packages/ui/src/demos/progress/with-value.tsx',
  },
  'prompt-input': {
    attachments: 'packages/ui/src/demos/prompt-input/attachments.tsx',
    default: 'packages/ui/src/demos/prompt-input/default.tsx',
    statuses: 'packages/ui/src/demos/prompt-input/statuses.tsx',
  },
  radio: {
    default: 'packages/ui/src/demos/radio/default.tsx',
    disabled: 'packages/ui/src/demos/radio/disabled.tsx',
    'with-label': 'packages/ui/src/demos/radio/with-label.tsx',
  },
  rating: {
    'custom-icon': 'packages/ui/src/demos/rating/custom-icon.tsx',
    default: 'packages/ui/src/demos/rating/default.tsx',
    half: 'packages/ui/src/demos/rating/half.tsx',
    'read-only': 'packages/ui/src/demos/rating/read-only.tsx',
    sizes: 'packages/ui/src/demos/rating/sizes.tsx',
  },
  reasoning: {
    default: 'packages/ui/src/demos/reasoning/default.tsx',
    streaming: 'packages/ui/src/demos/reasoning/streaming.tsx',
  },
  resizable: {
    default: 'packages/ui/src/demos/resizable/default.tsx',
    nested: 'packages/ui/src/demos/resizable/nested.tsx',
    vertical: 'packages/ui/src/demos/resizable/vertical.tsx',
  },
  response: {
    default: 'packages/ui/src/demos/response/default.tsx',
    streaming: 'packages/ui/src/demos/response/streaming.tsx',
  },
  'scroll-area': {
    both: 'packages/ui/src/demos/scroll-area/both.tsx',
    default: 'packages/ui/src/demos/scroll-area/default.tsx',
    horizontal: 'packages/ui/src/demos/scroll-area/horizontal.tsx',
  },
  'search-command': {
    controlled: 'packages/ui/src/demos/search-command/controlled.tsx',
    default: 'packages/ui/src/demos/search-command/default.tsx',
  },
  section: {
    backgrounds: 'packages/ui/src/demos/section/backgrounds.tsx',
    centered: 'packages/ui/src/demos/section/centered.tsx',
    default: 'packages/ui/src/demos/section/default.tsx',
  },
  select: {
    default: 'packages/ui/src/demos/select/default.tsx',
    'grouped-items': 'packages/ui/src/demos/select/grouped-items.tsx',
  },
  separator: {
    default: 'packages/ui/src/demos/separator/default.tsx',
    'with-label': 'packages/ui/src/demos/separator/with-label.tsx',
  },
  'settings-row': {
    danger: 'packages/ui/src/demos/settings-row/danger.tsx',
    default: 'packages/ui/src/demos/settings-row/default.tsx',
  },
  sheet: {
    default: 'packages/ui/src/demos/sheet/default.tsx',
    sides: 'packages/ui/src/demos/sheet/sides.tsx',
    sizes: 'packages/ui/src/demos/sheet/sizes.tsx',
  },
  shimmer: {
    default: 'packages/ui/src/demos/shimmer/default.tsx',
    sizes: 'packages/ui/src/demos/shimmer/sizes.tsx',
  },
  skeleton: {
    card: 'packages/ui/src/demos/skeleton/card.tsx',
    default: 'packages/ui/src/demos/skeleton/default.tsx',
  },
  sources: {
    default: 'packages/ui/src/demos/sources/default.tsx',
    open: 'packages/ui/src/demos/sources/open.tsx',
  },
  spacer: {
    default: 'packages/ui/src/demos/spacer/default.tsx',
    fixed: 'packages/ui/src/demos/spacer/fixed.tsx',
  },
  spinner: {
    default: 'packages/ui/src/demos/spinner/default.tsx',
    sizes: 'packages/ui/src/demos/spinner/sizes.tsx',
    variants: 'packages/ui/src/demos/spinner/variants.tsx',
  },
  split: {
    default: 'packages/ui/src/demos/split/default.tsx',
    ratios: 'packages/ui/src/demos/split/ratios.tsx',
    reverse: 'packages/ui/src/demos/split/reverse.tsx',
  },
  sprite: {
    default: 'packages/ui/src/demos/sprite/default.tsx',
    parts: 'packages/ui/src/demos/sprite/parts.tsx',
    seeds: 'packages/ui/src/demos/sprite/seeds.tsx',
    states: 'packages/ui/src/demos/sprite/states.tsx',
  },
  stack: {
    default: 'packages/ui/src/demos/stack/default.tsx',
  },
  suggestion: {
    default: 'packages/ui/src/demos/suggestion/default.tsx',
    variants: 'packages/ui/src/demos/suggestion/variants.tsx',
  },
  switch: {
    default: 'packages/ui/src/demos/switch/default.tsx',
    disabled: 'packages/ui/src/demos/switch/disabled.tsx',
    'with-label': 'packages/ui/src/demos/switch/with-label.tsx',
  },
  table: {
    compact: 'packages/ui/src/demos/table/compact.tsx',
    default: 'packages/ui/src/demos/table/default.tsx',
    striped: 'packages/ui/src/demos/table/striped.tsx',
    'with-actions': 'packages/ui/src/demos/table/with-actions.tsx',
  },
  tabs: {
    default: 'packages/ui/src/demos/tabs/default.tsx',
    vertical: 'packages/ui/src/demos/tabs/vertical.tsx',
  },
  task: {
    default: 'packages/ui/src/demos/task/default.tsx',
    statuses: 'packages/ui/src/demos/task/statuses.tsx',
  },
  textarea: {
    'auto-resize': 'packages/ui/src/demos/textarea/auto-resize.tsx',
    default: 'packages/ui/src/demos/textarea/default.tsx',
    'with-count': 'packages/ui/src/demos/textarea/with-count.tsx',
    'with-error': 'packages/ui/src/demos/textarea/with-error.tsx',
    'with-label': 'packages/ui/src/demos/textarea/with-label.tsx',
  },
  timeline: {
    alternate: 'packages/ui/src/demos/timeline/alternate.tsx',
    default: 'packages/ui/src/demos/timeline/default.tsx',
    horizontal: 'packages/ui/src/demos/timeline/horizontal.tsx',
    icons: 'packages/ui/src/demos/timeline/icons.tsx',
    'left-dates': 'packages/ui/src/demos/timeline/left-dates.tsx',
  },
  toast: {
    default: 'packages/ui/src/demos/toast/default.tsx',
    positions: 'packages/ui/src/demos/toast/positions.tsx',
    variants: 'packages/ui/src/demos/toast/variants.tsx',
    'with-action': 'packages/ui/src/demos/toast/with-action.tsx',
  },
  tool: {
    default: 'packages/ui/src/demos/tool/default.tsx',
    statuses: 'packages/ui/src/demos/tool/statuses.tsx',
  },
  tooltip: {
    default: 'packages/ui/src/demos/tooltip/default.tsx',
    positions: 'packages/ui/src/demos/tooltip/positions.tsx',
  },
  tree: {
    default: 'packages/ui/src/demos/tree/default.tsx',
    icons: 'packages/ui/src/demos/tree/icons.tsx',
    lines: 'packages/ui/src/demos/tree/lines.tsx',
    'plus-minus': 'packages/ui/src/demos/tree/plus-minus.tsx',
  },
  typography: {
    'custom-tag': 'packages/ui/src/demos/typography/custom-tag.tsx',
    default: 'packages/ui/src/demos/typography/default.tsx',
    headings: 'packages/ui/src/demos/typography/headings.tsx',
    'lead-muted': 'packages/ui/src/demos/typography/lead-muted.tsx',
  },
} as const;

/** Gallery examples: real compositions built with a component, never shown in docs. */
export const EXAMPLE_REGISTRY = {
  accordion: {
    icons: 'packages/ui/src/examples/accordion/icons.tsx',
  },
  avatar: {
    team: 'packages/ui/src/examples/avatar/team.tsx',
  },
  badge: {
    statuses: 'packages/ui/src/examples/badge/statuses.tsx',
  },
  bubble: {
    attachments: 'packages/ui/src/examples/bubble/attachments.tsx',
  },
  button: {
    toolbar: 'packages/ui/src/examples/button/toolbar.tsx',
  },
  card: {
    stats: 'packages/ui/src/examples/card/stats.tsx',
  },
  'context-menu': {
    'track-list': 'packages/ui/src/examples/context-menu/track-list.tsx',
  },
  dialog: {
    confirm: 'packages/ui/src/examples/dialog/confirm.tsx',
  },
  empty: {
    inbox: 'packages/ui/src/examples/empty/inbox.tsx',
  },
  'file-upload': {
    documents: 'packages/ui/src/examples/file-upload/documents.tsx',
  },
  frame: {
    nested: 'packages/ui/src/examples/frame/nested.tsx',
  },
  'icon-tile': {
    'feature-list': 'packages/ui/src/examples/icon-tile/feature-list.tsx',
  },
  input: {
    'sign-in': 'packages/ui/src/examples/input/sign-in.tsx',
  },
  message: {
    assistant: 'packages/ui/src/examples/message/assistant.tsx',
  },
  pagination: {
    table: 'packages/ui/src/examples/pagination/table.tsx',
  },
  switch: {
    preferences: 'packages/ui/src/examples/switch/preferences.tsx',
  },
  tabs: {
    settings: 'packages/ui/src/examples/tabs/settings.tsx',
  },
  timeline: {
    deployments: 'packages/ui/src/examples/timeline/deployments.tsx',
  },
} as const;

export const BRICK_REGISTRY = {
  dashboard: {
    'dashboard-01': 'packages/ui/src/bricks/dashboard/dashboard-01',
    'dashboard-02': 'packages/ui/src/bricks/dashboard/dashboard-02',
  },
  login: {
    'login-01': 'packages/ui/src/bricks/login/login-01',
    'login-02': 'packages/ui/src/bricks/login/login-02',
    'login-03': 'packages/ui/src/bricks/login/login-03',
  },
  pricing: {
    'pricing-01': 'packages/ui/src/bricks/pricing/pricing-01',
    'pricing-02': 'packages/ui/src/bricks/pricing/pricing-02',
  },
  settings: {
    'settings-01': 'packages/ui/src/bricks/settings/settings-01',
    'settings-02': 'packages/ui/src/bricks/settings/settings-02',
  },
  signup: {
    'signup-01': 'packages/ui/src/bricks/signup/signup-01',
    'signup-02': 'packages/ui/src/bricks/signup/signup-02',
  },
} as const;

/** The icon set: one self-contained file per icon, served as the `icons` family. */
export const ICONS_DIR = 'src/icons';
export const ICON_REGISTRY = {
  'alert-circle': 'packages/ui/src/icons/alert-circle.tsx',
  'alert-triangle': 'packages/ui/src/icons/alert-triangle.tsx',
  'align-center': 'packages/ui/src/icons/align-center.tsx',
  archive: 'packages/ui/src/icons/archive.tsx',
  'arrow-down': 'packages/ui/src/icons/arrow-down.tsx',
  'arrow-left': 'packages/ui/src/icons/arrow-left.tsx',
  'arrow-right': 'packages/ui/src/icons/arrow-right.tsx',
  'arrow-up': 'packages/ui/src/icons/arrow-up.tsx',
  'arrow-up-right': 'packages/ui/src/icons/arrow-up-right.tsx',
  'bar-chart': 'packages/ui/src/icons/bar-chart.tsx',
  bell: 'packages/ui/src/icons/bell.tsx',
  book: 'packages/ui/src/icons/book.tsx',
  bookmark: 'packages/ui/src/icons/bookmark.tsx',
  browser: 'packages/ui/src/icons/browser.tsx',
  calendar: 'packages/ui/src/icons/calendar.tsx',
  camera: 'packages/ui/src/icons/camera.tsx',
  cards: 'packages/ui/src/icons/cards.tsx',
  check: 'packages/ui/src/icons/check.tsx',
  'check-circle': 'packages/ui/src/icons/check-circle.tsx',
  'check-square': 'packages/ui/src/icons/check-square.tsx',
  'chevron-down': 'packages/ui/src/icons/chevron-down.tsx',
  'chevron-left': 'packages/ui/src/icons/chevron-left.tsx',
  'chevron-right': 'packages/ui/src/icons/chevron-right.tsx',
  'chevron-up': 'packages/ui/src/icons/chevron-up.tsx',
  'chevrons-down-up': 'packages/ui/src/icons/chevrons-down-up.tsx',
  'chevrons-up-down': 'packages/ui/src/icons/chevrons-up-down.tsx',
  'circle-dot': 'packages/ui/src/icons/circle-dot.tsx',
  clock: 'packages/ui/src/icons/clock.tsx',
  'cloud-upload': 'packages/ui/src/icons/cloud-upload.tsx',
  code: 'packages/ui/src/icons/code.tsx',
  copy: 'packages/ui/src/icons/copy.tsx',
  'corner-down-left': 'packages/ui/src/icons/corner-down-left.tsx',
  'credit-card': 'packages/ui/src/icons/credit-card.tsx',
  cursor: 'packages/ui/src/icons/cursor.tsx',
  'distribute-horizontal': 'packages/ui/src/icons/distribute-horizontal.tsx',
  download: 'packages/ui/src/icons/download.tsx',
  'external-link': 'packages/ui/src/icons/external-link.tsx',
  eye: 'packages/ui/src/icons/eye.tsx',
  'eye-off': 'packages/ui/src/icons/eye-off.tsx',
  file: 'packages/ui/src/icons/file.tsx',
  'file-text': 'packages/ui/src/icons/file-text.tsx',
  'file-up': 'packages/ui/src/icons/file-up.tsx',
  filter: 'packages/ui/src/icons/filter.tsx',
  folder: 'packages/ui/src/icons/folder.tsx',
  'folder-open': 'packages/ui/src/icons/folder-open.tsx',
  frame: 'packages/ui/src/icons/frame.tsx',
  gamepad: 'packages/ui/src/icons/gamepad.tsx',
  gauge: 'packages/ui/src/icons/gauge.tsx',
  'git-commit': 'packages/ui/src/icons/git-commit.tsx',
  'git-merge': 'packages/ui/src/icons/git-merge.tsx',
  globe: 'packages/ui/src/icons/globe.tsx',
  grid: 'packages/ui/src/icons/grid.tsx',
  'grip-vertical': 'packages/ui/src/icons/grip-vertical.tsx',
  heart: 'packages/ui/src/icons/heart.tsx',
  'help-circle': 'packages/ui/src/icons/help-circle.tsx',
  history: 'packages/ui/src/icons/history.tsx',
  home: 'packages/ui/src/icons/home.tsx',
  image: 'packages/ui/src/icons/image.tsx',
  'image-plus': 'packages/ui/src/icons/image-plus.tsx',
  inbox: 'packages/ui/src/icons/inbox.tsx',
  info: 'packages/ui/src/icons/info.tsx',
  key: 'packages/ui/src/icons/key.tsx',
  keyboard: 'packages/ui/src/icons/keyboard.tsx',
  languages: 'packages/ui/src/icons/languages.tsx',
  laptop: 'packages/ui/src/icons/laptop.tsx',
  layers: 'packages/ui/src/icons/layers.tsx',
  layout: 'packages/ui/src/icons/layout.tsx',
  'layout-grid': 'packages/ui/src/icons/layout-grid.tsx',
  link: 'packages/ui/src/icons/link.tsx',
  loader: 'packages/ui/src/icons/loader.tsx',
  lock: 'packages/ui/src/icons/lock.tsx',
  'log-out': 'packages/ui/src/icons/log-out.tsx',
  mail: 'packages/ui/src/icons/mail.tsx',
  maximize: 'packages/ui/src/icons/maximize.tsx',
  megaphone: 'packages/ui/src/icons/megaphone.tsx',
  menu: 'packages/ui/src/icons/menu.tsx',
  'message-circle': 'packages/ui/src/icons/message-circle.tsx',
  'message-plus': 'packages/ui/src/icons/message-plus.tsx',
  minus: 'packages/ui/src/icons/minus.tsx',
  moon: 'packages/ui/src/icons/moon.tsx',
  'more-horizontal': 'packages/ui/src/icons/more-horizontal.tsx',
  'more-vertical': 'packages/ui/src/icons/more-vertical.tsx',
  music: 'packages/ui/src/icons/music.tsx',
  navigation: 'packages/ui/src/icons/navigation.tsx',
  package: 'packages/ui/src/icons/package.tsx',
  palette: 'packages/ui/src/icons/palette.tsx',
  'panel-left': 'packages/ui/src/icons/panel-left.tsx',
  'panel-right': 'packages/ui/src/icons/panel-right.tsx',
  paperclip: 'packages/ui/src/icons/paperclip.tsx',
  pencil: 'packages/ui/src/icons/pencil.tsx',
  plus: 'packages/ui/src/icons/plus.tsx',
  puzzle: 'packages/ui/src/icons/puzzle.tsx',
  rectangle: 'packages/ui/src/icons/rectangle.tsx',
  refresh: 'packages/ui/src/icons/refresh.tsx',
  repeat: 'packages/ui/src/icons/repeat.tsx',
  rocket: 'packages/ui/src/icons/rocket.tsx',
  route: 'packages/ui/src/icons/route.tsx',
  search: 'packages/ui/src/icons/search.tsx',
  send: 'packages/ui/src/icons/send.tsx',
  'separator-horizontal': 'packages/ui/src/icons/separator-horizontal.tsx',
  server: 'packages/ui/src/icons/server.tsx',
  settings: 'packages/ui/src/icons/settings.tsx',
  share: 'packages/ui/src/icons/share.tsx',
  shield: 'packages/ui/src/icons/shield.tsx',
  sparkles: 'packages/ui/src/icons/sparkles.tsx',
  square: 'packages/ui/src/icons/square.tsx',
  star: 'packages/ui/src/icons/star.tsx',
  sun: 'packages/ui/src/icons/sun.tsx',
  table: 'packages/ui/src/icons/table.tsx',
  tag: 'packages/ui/src/icons/tag.tsx',
  terminal: 'packages/ui/src/icons/terminal.tsx',
  'text-cursor-input': 'packages/ui/src/icons/text-cursor-input.tsx',
  toggle: 'packages/ui/src/icons/toggle.tsx',
  trash: 'packages/ui/src/icons/trash.tsx',
  type: 'packages/ui/src/icons/type.tsx',
  upload: 'packages/ui/src/icons/upload.tsx',
  user: 'packages/ui/src/icons/user.tsx',
  'user-circle': 'packages/ui/src/icons/user-circle.tsx',
  'user-plus': 'packages/ui/src/icons/user-plus.tsx',
  users: 'packages/ui/src/icons/users.tsx',
  video: 'packages/ui/src/icons/video.tsx',
  wand: 'packages/ui/src/icons/wand.tsx',
  x: 'packages/ui/src/icons/x.tsx',
  'x-circle': 'packages/ui/src/icons/x-circle.tsx',
  zap: 'packages/ui/src/icons/zap.tsx',
} as const;

export type Family = (typeof FAMILIES)[number]['id'];
export type ComponentName = keyof typeof COMPONENT_REGISTRY;
export type DemoName<T extends keyof typeof DEMO_REGISTRY> = keyof (typeof DEMO_REGISTRY)[T];
export type ExampleName<T extends keyof typeof EXAMPLE_REGISTRY> = keyof (typeof EXAMPLE_REGISTRY)[T];
export type BrickCategory = keyof typeof BRICK_REGISTRY;
export type BrickName<T extends BrickCategory> = keyof (typeof BRICK_REGISTRY)[T];
export type IconName = keyof typeof ICON_REGISTRY;
